spring:
  cloud:
    config:
      server:
        git:
          uri: ${$git.uri:https://github.com/nds-examples/properties-examples.git}
          username : ${git.user}
          password : ${git.pwd}
          search-paths: common, ${current.environment:developer}
server:
  port: 8888
